### Import all the necessary library

In [1]:
import pandas as pd

### Load the provided Dataset

In [2]:
# code here
from pathlib import Path

data_path = Path("Assignments/Assignment 11/Coded_Data.csv")
if not data_path.exists():
    data_path = Path("Coded_Data.csv")

df = pd.read_csv(data_path)
df

,Unnamed: 0,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10,Result
0,1,53.1,63.4,33.0,46.2,47.3,21.2,44.3,36.1,46.6,65.0,Y
1,2,36.9,54.7,31.1,50.5,56.0,38.9,39.4,56.8,33.0,78.8,N
2,3,41.9,65.5,53.5,52.3,92.5,43.2,94.9,64.7,50.8,67.9,N
3,4,71.7,75.6,37.9,50.5,69.2,52.5,82.3,77.3,80.8,60.9,Y
4,5,74.3,51.8,36.4,40.9,74.7,42.2,65.1,36.2,77.6,74.9,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,58.7,56.4,49.5,38.1,62.8,35.2,43.6,17.9,59.3,71.2,Y
996,997,33.4,52.1,54.7,48.5,85.7,76.2,61.6,40.0,50.8,87.8,N
997,998,66.0,53.6,45.4,56.1,54.6,53.1,22.6,21.8,48.8,73.2,Y
998,999,63.0,47.0,23.6,40.7,97.5,56.6,50.0,59.4,67.7,62.7,Y
999,1000,48.6,52.4,24.2,48.9,56.6,25.5,45.4,50.9,66.7,72.1,Y

,Unnamed: 0,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10,Result
0,1,53.1,63.4,33.0,46.2,47.3,21.2,44.3,36.1,46.6,65.0,Y
1,2,36.9,54.7,31.1,50.5,56.0,38.9,39.4,56.8,33.0,78.8,N
2,3,41.9,65.5,53.5,52.3,92.5,43.2,94.9,64.7,50.8,67.9,N
3,4,71.7,75.6,37.9,50.5,69.2,52.5,82.3,77.3,80.8,60.9,Y
4,5,74.3,51.8,36.4,40.9,74.7,42.2,65.1,36.2,77.6,74.9,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,58.7,56.4,49.5,38.1,62.8,35.2,43.6,17.9,59.3,71.2,Y
996,997,33.4,52.1,54.7,48.5,85.7,76.2,61.6,40.0,50.8,87.8,N
997,998,66.0,53.6,45.4,56.1,54.6,53.1,22.6,21.8,48.8,73.2,Y
998,999,63.0,47.0,23.6,40.7,97.5,56.6,50.0,59.4,67.7,62.7,Y
999,1000,48.6,52.4,24.2,48.9,56.6,25.5,45.4,50.9,66.7,72.1,Y

### In our dataframe, the first column looks like the index, let's set `index_col = 0`

In [3]:
# code here

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

Great, this looks fine now!<br>

Let's overview the data, we can use `info()` here!

In [ ]:
#Code here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cd_1    1000 non-null   float64
 1   Cd_2    1000 non-null   float64
 2   Cd_3    1000 non-null   float64
 3   Cd_4    1000 non-null   float64
 4   Cd_5    1000 non-null   float64
 5   Cd_6    1000 non-null   float64
 6   Cd_7    1000 non-null   float64
 7   Cd_8    1000 non-null   float64
 8   Cd_9    1000 non-null   float64
 9   Cd_10   1000 non-null   float64
 10  Result  1000 non-null   object
dtypes: float64(10), object(1)
memory usage: 86.1+ KB

Let's split the data so that we can fit the `scaler` to the features only!

In [7]:
#Code Here

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1

[1000 rows x 10 columns]

Let's fit `scaler` to the features now!

In [9]:
#Code here

StandardScaler()

So, we have the fitted features to the `scaler` object. We will use this `scaler` object to transform all the features using `.transform()` method in `Scikit-learn` to do the `standardization` job by centering and scaling.<br>
Let's pass the features to `scaler.transform()` to get standardized features in `scaled_features`!

In [11]:
# code here

In [12]:
scaled_features

array([[-0.12252539,  0.1875694 , -0.91183199, ..., -1.48006982,
        -0.95256187, -0.64536551],
       [-1.08602779, -0.43340316, -1.02415132, ..., -0.20055606,
        -1.82621843,  0.6351032 ],
       [-0.78865051,  0.33745933,  0.30003449, ...,  0.28776079,
        -0.68275617, -0.3762815 ],
       ...,
       [ 0.64470801, -0.51191693, -0.17880055, ..., -2.36398512,
        -0.81123508,  0.11549271],
       [ 0.46628164, -0.98299956, -1.46751711, ..., -0.03984418,
         0.40289057, -0.85877696],
       [-0.39016495, -0.59756832, -1.43204784, ..., -0.56524838,
         0.33865112,  0.01342636]])

In [13]:
scaled_features.shape

(1000, 10)

`scaled_features` is a NumPy array, Let's convert this into the pandas `DataFrame`!<br>
We can use our `df.columns` to get the columns name and pass that to `DatFrame()` along with `scaled_features`, note we don't need `Results` column, [:-1] will work *(everything but the last one)*!

In [14]:
#Before Scaling
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

In [15]:
# column

Index(['Cd_1', 'Cd_2', 'Cd_3', 'Cd_4', 'Cd_5', 'Cd_6', 'Cd_7', 'Cd_8', 'Cd_9',
       'Cd_10'],
      dtype='object')

### Create the below output

In [ ]:
# code here

In [16]:
#After Scaling

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
0,-0.122525,0.187569,-0.911832,0.318653,-1.035516,-2.305940,-0.801865,-1.480070,-0.952562,-0.645366
1,-1.086028,-0.433403,-1.024151,0.624941,-0.445471,-1.153296,-1.131088,-0.200556,-1.826218,0.635103
2,-0.788651,0.337459,0.300034,0.753154,2.030007,-0.873275,2.597862,0.287761,-0.682756,-0.376282
3,0.983718,1.058359,-0.622166,0.624941,0.449771,-0.267648,1.751290,1.066595,1.244427,-1.025795
4,1.138354,-0.640394,-0.710839,-0.058864,0.822788,-0.938396,0.595651,-1.473889,1.038861,0.273232
...,...,...,...,...,...,...,...,...,...,...
995,0.210537,-0.312064,0.063573,-0.258307,0.015714,-1.394244,-0.848897,-2.605053,-0.136721,-0.070082
996,-1.294192,-0.618981,0.370973,0.482481,1.568822,1.275723,0.360492,-1.239002,-0.682756,1.470191
997,0.644708,-0.511917,-0.178801,1.023827,-0.540420,-0.228575,-2.259851,-2.363985,-0.811235,0.115493
998,0.466282,-0.983000,-1.467517,-0.073110,2.369113,-0.000651,-0.418892,-0.039844,0.402891,-0.858777
999,-0.390165,-0.597568,-1.432048,0.510973,-0.404778,-2.025919,-0.727958,-0.565248,0.338651,0.013426

<br>Our data is ready for the Machine Learning part now!
## Let's do the train_test split 
I am sure, you are very comfortable with this now!

In [17]:
# Code here

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
505,-1.193084,1.201111,0.684285,-0.479119,-1.883282,1.725059,0.071582,0.361936,-1.633500,-1.118582
547,1.043194,-1.518321,-0.592609,-0.685685,-1.103337,0.644048,0.844248,-0.237643,-0.708452,1.395961
75,-0.063050,1.094047,0.329592,-0.977727,1.365358,-0.599766,0.871123,1.017145,-0.104601,0.291789
960,-0.752965,0.972707,0.081307,-0.600210,-1.320365,1.894374,-1.245308,0.293942,0.011030,-0.051525
557,-1.573727,-0.611844,0.016280,0.190440,0.314128,-1.882653,1.610194,0.825527,-1.061769,-0.385560
...,...,...,...,...,...,...,...,...,...,...
844,-0.122525,-1.703899,0.406442,1.194778,-0.716756,1.633890,-0.385298,-1.554245,1.347211,0.746448
424,0.775554,1.343863,0.022192,0.290161,-1.021952,-0.469524,-0.902648,1.938148,-0.946138,-0.172149
574,0.020216,-1.504046,-0.598520,-0.536103,1.053380,1.015239,-0.136701,-1.257546,0.043150,1.201107
154,-0.925444,0.358872,0.181804,-0.350906,1.636643,-0.756057,2.013324,0.590641,-1.190248,-0.125755
947,1.869902,-0.476229,1.925709,-0.009003,-0.486163,-0.274160,0.427680,-0.280912,1.681256,-0.710317

In [ ]:
# code here

505    N
547    Y
75     N
960    N
557    N
      ..
844    Y
424    N
574    Y
154    N
947    Y
Name: Result, Length: 700, dtype: object

In [ ]:
# code here to show test dataset

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
305,-2.174429,-1.175715,1.559193,0.404129,-0.275917,0.364027,1.428786,1.276757,-0.914018,-2.890825
826,0.870715,-2.203532,-0.663547,1.693385,-2.358031,-1.485414,-0.721239,-0.231462,-0.804811,-0.367003
442,0.335436,-0.419128,0.116777,-1.312506,-1.591651,-1.205393,-1.675313,-0.138744,0.647000,-1.823768
990,-0.253371,-0.668944,0.778870,3.467004,-0.879527,2.070202,1.348160,0.782259,-2.166688,-0.376282
312,0.870715,0.637239,-1.242878,1.465451,-0.242007,-1.309586,2.671769,-0.076932,-0.008242,-1.378387
...,...,...,...,...,...,...,...,...,...,...
33,0.394911,0.979845,0.690196,0.197563,0.253089,0.377052,-0.902648,0.306304,1.629864,0.783563
232,-1.222821,1.379551,0.826162,-1.006219,-1.320365,0.409612,1.455661,-0.089294,-0.175264,-0.237100
933,0.329488,-0.354889,-0.852717,0.731785,-1.116902,0.735218,0.461275,-1.863306,1.822582,-1.016516
71,-0.306899,1.586542,0.400531,-1.127309,-1.829025,-0.547669,0.521744,-0.577611,0.248716,-0.302051
713,1.221620,0.708615,0.477381,-0.443504,-1.021952,-0.098333,-0.486080,-2.246542,1.096677,-1.842325

## KNN
Our focus is to come up with a model that can predict the class in `Result` for the new data point. We don't know what k number will work best, let's start with k = 1 at the moment. <br>
We need to import the `KNeighborsClassifier` from `sklearn.neighbors`.

In [22]:
#Code here

KNeighborsClassifier(n_neighbors=3)

Let's show the score now!

In [ ]:
#Code here