In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("canada_pincome.csv")

In [60]:
df.head()

   year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [66]:
df.rename(columns={"per capita income (US$)": "pc_income"}, inplace=True)
df.head()

   year    pc_income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [67]:
print(df.dtypes)

year           int64
pc_income    float64
dtype: object

In [68]:
df.sort_values(by="year")
X = df[['year']]
X.head()

   year
0  1970
1  1971
2  1972
3  1973
4  1974

In [69]:
Y = df[['pc_income']]
Y.head()

     pc_income
0  3399.299037
1  3768.297935
2  4251.175484
3  4804.463248
4  5576.514583

In [79]:
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(X,Y)

split_index = int(len(df) * 0.8)
X_train = X[:split_index]
X_test = X[split_index:]

Y_train = Y[:split_index]
Y_test = Y[split_index:]

In [80]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [82]:
# Y_pred = model.predict(X)
Y_pred = model.predict(X_test)

In [83]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np
r2 = r2_score(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)

print("R2:", r2)
print("MSE:", mse)
print("RMSE:", rmse)
# print(r2_score(Y_test,Y_pred))

R2: -8.350800286581574
MSE: 116383635.82617863
RMSE: 10788.124759483393