In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("canada_pincome.csv")

In [4]:
df.head()

   year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [21]:
df.rename(columns={"income": "pc_income"}, inplace=True)
df.head()

   year    pc_income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [23]:
print(df.dtypes)

year           int64
pc_income    float64
dtype: object

In [26]:
X = df[['year']]
X.head()

   year
0  1970
1  1971
2  1972
3  1973
4  1974

In [30]:
Y = df[['pc_income']]
Y.head()

     pc_income
0  3399.299037
1  3768.297935
2  4251.175484
3  4804.463248
4  5576.514583

In [ ]:
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(X,Y)

split_index = int(len(df) * 0.9)
X_train = X[:split_index]
X_test = X[split_index:]

Y_train = Y[:split_index]
Y_test = Y[split_index:]

42

In [ ]:
# Y_pred = model.predict(X)